#!/usr/bin/env bash
# h-config.sh — HiveOS config generator for cpuminer-opt-cpupower (civiclight).
#
# HiveOS's miner-run requires h-config.sh to exist and be executable in the
# custom miner dir (/hive/miners/custom/<miner>/), or it aborts with
# "Miner installing error, not found command file".
#
# The actual launch (cpuminer.sh) reads the flight-sheet wallet.conf directly,
# so this script only needs to (a) succeed and (b) emit a small miner.conf for
# HiveOS compatibility / operator visibility.  It mirrors the flight-sheet
# values (template = address.worker, url = pool) into miner.conf.

# Detect script location
[[ -z $SCRIPT_PATH ]] && SCRIPT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
[[ -z $MINER_DIR ]] && MINER_DIR=/hive/miners/custom

# Source manifest
[[ -f $SCRIPT_PATH/h-manifest.conf ]] && source "$SCRIPT_PATH/h-manifest.conf"

conf_file="${CUSTOM_CONFIG_FILENAME:-$MINER_DIR/$MINER_NAME/miner.conf}"

wallet="${CUSTOM_TEMPLATE:-}"
pass="${CUSTOM_PASS:-x}"
pool="${CUSTOM_URL:-}"

{
    printf '# generated by h-config.sh — do not edit by hand\n'
    printf 'POOL_URL=%q\n' "$pool"
    printf 'WALLET=%q\n' "$wallet"
    printf 'PASS=%q\n' "$pass"
} > "$conf_file"

echo "Configuration written to $conf_file"
echo "Pool: $pool"
echo "Wallet: $wallet"

# HiveOS miner_config_gen sources this file; the sourced return status is treated
# as config success, so the final command MUST exit 0.
return 0 2>/dev/null || exit 0
